Portfolio: setup and mobile version skeleton
Mugiira-Kim/Portfolio-mobileskeleton pull request #1
Opened 2022-04-20 15:01 UTC by Mugiira-Kim

**In this exercise I was able to do the following;**

Parse a Figma design to create a UI.
Use Flexbox to place elements in the page.
Build a personal portfolio site.
Use images and backgrounds to enhance the look of the website.

2022-04-20 18:05 UTC, AnselemOdims requested changes
### Hi @Mugiira-Kim , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-20 18:05 UTC, AnselemOdims commented on index.html
> +<div class="container">
- [ ] Please ensure that the `headline section` and subsequent sections are wrapped in a section tag

2022-04-20 18:05 UTC, AnselemOdims commented on index.html
> +    </header>
- Kindly remove the `header` element enclosing the name. A `heading` might not necessarily be a `header`. In this case, it is not

2022-04-20 18:05 UTC, AnselemOdims commented on index.html
> +        I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded, don’t he
- [ ] Please kindly wrap this text in a paragraph `p` tag for semantic purposes.

2022-04-20 18:05 UTC, AnselemOdims commented on index.html
> +            <i class="fa-solid fa-hand-peace"></i>
- [ ] Please ensure that the list of icons are wrapped in a `ul` tag, with items individually wrapped in an `li` tag
- [ ] Please also stick with the icons that were specified in the original design. You can export them from the figma doc

### Hint
```
<ul>
  <li><a><img src="" /></a></li>
</ul>
```

2022-04-20 18:05 UTC, AnselemOdims commented on index.html
> +        <a href="">Contact</a>
- [ ] Good job working on this, but this milestone focuses on the mobile version. While you will have the opportunity to design for desktop later, please make sure at the moment it is mobile-focused. Please replace the links with a hamburger as specified in the design.

### Your Design
![image](https://user-images.githubusercontent.com/43995830/164293617-65430dda-2d56-4add-93af-75ede787293a.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/164293908-ce077674-b135-4a8a-8c47-22fe8a93b21b.png)

2022-04-20 18:05 UTC, AnselemOdims commented on style.css
> +    background-image: url(./images/headerbg.svg);
- [ ] Kindly ensure the background image is properly positioned as it is in the original design. You can also remove it from the body element and put it in the appropriate section
- [ ] Also, please try to adjust your screen to remove horizontal scrolling as it does not give a good user experience

2022-04-21 04:06 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @Mugiira-Kim,
> Nice job, you are almost there.
> 
> ![TryAgain](https://user-images.githubusercontent.com/52934128/164369915-c0348845-299f-4e1c-ab76-9f3e3b5be748.gif)

> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-21 04:06 UTC, topeogunleye commented on index.html
> +<div class="container">
- [ ] [REQUIRED]  As suggested by the previous code reviewer, I kindly suggest that you change this `div` tag to a `section` in order to follow project requirements and be more [semantic](https://developer.mozilla.org/en-US/docs/Glossary/Semantics)

2022-04-21 04:06 UTC, topeogunleye commented on index.html
> +           <a><img src="socials.png" alt="media-icons" /></a>
- [ ] [REQUIRED] As the previous code reviewer suggested. I kindly suggest you stick with the icons that were specified in the original design. Please import each icon individually and use a ul tag to group them, and li per icon; each icon having a link

Here is a video tutorial on how to export icons from the figma doc:
https://user-images.githubusercontent.com/52934128/164367732-19a29775-a4a7-410d-b67c-2267b629673c.mp4


### Here is an Example of How to Implement the Media Icons:
```
<ul class="social_links">
                <li>
                  <a
                    href="https://twitter.com/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <img
                      src="./images/svg/Twitter-icon.svg"
                      alt="link to twitter"
                      class="social_icon"
                  /></a>
                </li>
                <li>
                  <a
                    href="https://www.linkedin.com/in/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <img
                      src="./images/svg/Linkedin-icon.svg"
                      alt="link to linkedin"
                      class="social_icon"
                  /></a>
                </li>
                <li>
                  <a
                    href="https://www.medium.com/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <img
                      src="./images/svg/Medium-icon.svg"
                      alt="link to medium"
                      class="social_icon"
                    />
                  </a>
                </li>
                <li>
                  <a
                    href="https://github.com/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <img
                      src="./images/svg/Github-icon.svg"
                      alt="link to github"
                      class="social_icon"
                    />
                  </a>
                </li>
                <li>
                  <a href="" target="_blank" rel="noopener noreferrer">
                    <img
                      src="./images/svg/Vector.svg"
                      alt="Vector icon"
                      class="social_icon"
                  /></a>
                </li>
              </ul>
```

2022-04-21 04:06 UTC, topeogunleye commented on style.css
> +    background-image: url(mobilebg.svg);
- [ ] [REQUIRED] As the previous code reviewer suggested.Kindly ensure the background image is properly displayed as it is in the original design.

| Your Portfolio | Template Design |
| ------------- | ------------- |
| ![Screenshot from 2022-04-21 04-57-18](https://user-images.githubusercontent.com/52934128/164369467-ebb86ae7-1029-4103-88ea-d62e253a2ccd.png)  | ![Screenshot from 2022-04-21 05-00-43](https://user-images.githubusercontent.com/52934128/164369538-8711c894-18dc-475a-bf39-dc8034f9b683.png) |

2022-04-21 20:01 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️ 

Hi @Mugiira-Kim,

Good job so far!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/164543041-823034a1-6f40-4e7c-a376-3671c74475e7.gif)

You are doing great in making some of the changes asked by the previous reviewers, but there are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

```

2022-04-21 20:01 UTC, AmaduKamara commented on index.html
> +    <div class="title">
[ REQUIRED CHANGES ]

- [ ] It would be nice if you could consider making the changes asked by the previous reviewer by changing this `div` tag to a `section` tag, it makes your code semantic and it's a requirement for the project.  It's okay giving it a class of `section-two`, but the idea here is for you to change the `div` to a `section` tag and then you can still maintain the class you used.
- Hint:
```mdx
<section class="section-two"></section>
```
👍 Kindly change that `div` to a section and your codebase will be good.

2022-04-21 22:10 UTC, koomekevo approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: 
Hi @Mugiira-Kim, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] Your README and Pull Request are descriptive.
- [ ] Your project is free of linter errors.

## Optional suggestions

- [ ] Kindly reduce the space as shown in the below screenshot.

![Mugiira Edited](https://user-images.githubusercontent.com/87413774/164559814-6cee3f9f-3385-4e12-9b7a-cadb2e52b61e.png)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 06:50 UTC, merged