Portfolio: mobile version
Mugiira-Kim/Portfolio-mobileskeleton pull request #2
Opened 2022-04-22 14:59 UTC by Mugiira-Kim

**In this exercise I was able to do the following:**

Build a personal portfolio site
Parse a Figma design to create a UI.
Use Flexbox to place elements in the page.

2022-04-22 19:07 UTC, codepantha requested changes
Hi @Mugiira-Kim 👋, 

## STATUS: REQUESTED CHANGES ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/Qaxd5XpgDWMso/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 19:07 UTC, codepantha commented on index.html
> +
- [ ] Please create a new `section` tag which should wrap around all your project cards. use CSS Grid in the main container that contains all of the cards, and use Flexbox to lay out an individual card.
- [ ] Please look at the snippet below, and remove the `<section>` tag as it is inappropriate in this case. You can use `<figure>` or even a generic `<div>` here.
```
<section class="image">
     <img src="imageone.png" alt="imageone">
 </section>
```

2022-04-22 19:07 UTC, codepantha commented on index.html
> +       </section>
- [ ] You are using `<section>` tag wrongly. I noticed you are using it everywhere. The Section tag defines the section of documents such as chapters, headers, footers or any other sections. Please remove every `<section>` tag from your code that is not explicitly diving the page into it's different parts like intro, works, about, footer etc.
- [ ] Please I will not point out everywhere you used section because it's virtually everywhere but you have to remove them all and use the appropriate semantic tags🙏

2022-04-22 19:07 UTC, codepantha commented on index.html
> +        </section>
- [ ] Your list of project technologies should have a `<ul>` container and each item should be a `<li>` as it's more semantic to use unordered lists to represent a list of things in HTML. Please effect this change 🙏

2022-04-22 19:07 UTC, codepantha commented on index.html
> +       </section>
- [ ] Your list of project technologies should have a `<ul>` container and each item should be a `<li>` as it's more semantic to use unordered lists to represent a list of things in HTML. Please effect this change 🙏

2022-04-22 19:07 UTC, codepantha commented on index.html
> +        </section>
- [ ] Please use unordered lists. Reference previous suggestions ☝️

2022-04-22 19:07 UTC, codepantha commented on index.html
> +        </section>
- [ ] Please reference  previous suggestions about `<ul>`

2022-04-22 19:07 UTC, codepantha commented on style.css
> +  }
- [ ] I noticed that you have `.works`, `.works-two`, three, and four but they all have the same styles. This is redundant. Please get rid of all other works variants and use only `.works` so that your code is cleaner. The DRY principle says 'Do not repeat yourself`.

2022-04-22 19:07 UTC, codepantha commented on index.html
> +    </section>
- [ ] The About me should be a heading `<hx>` and not a `<p>` tag.
- [ ] Please don't forget my earlier suggestion about your use of `<section>` tags

2022-04-22 19:07 UTC, codepantha commented on index.html
> +          <ul>
- [ ] Please use a header tag here instead of a paragraph. You could use a `<h3>` or `<h4>`

2022-04-22 19:07 UTC, codepantha commented on index.html
> +            </section>
- [ ] The technology in each category(e.g., "JavasScript", "HTML" and "CSS") should be `ul` and each of them a `li`

2022-04-22 19:07 UTC, codepantha commented on index.html
> +   </section>
- [ ] Your technologies  categories ("Languages", "Frameworks" and "Skills") are in a ul, each of them in a li

2022-04-23 10:22 UTC, Emmyn5600 requested changes
Hi @Mugiira-Kim 

Good job so far! I know you have worked hard on making this milestone. There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## Required Changes :recycle:
- [ ] Check the comments under the review too.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!:clap::clap::clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 10:22 UTC, Emmyn5600 commented on index.html
> +       <section class="project-title">
- [ ] Kindly remove the gap or blank space that is between the works and heading section.

![image](https://user-images.githubusercontent.com/55635977/164890148-2685bfd1-4dba-4962-a5fd-d222bf3d0c91.png)

2022-04-23 10:22 UTC, Emmyn5600 commented on index.html
> +<hr>
- [ ] Kindly make sure you follow the design provided to meet the requirements.

- [ ] Your design 
![image](https://user-images.githubusercontent.com/55635977/164890240-f1873cec-76de-4149-9411-b366224ba283.png)

- [ ] The design provided
![image](https://user-images.githubusercontent.com/55635977/164890315-8e7b7286-5dfe-4a8b-bd02-e47964211139.png)

You can check the padding, the arrow direction on the design and font family.

2022-04-23 10:22 UTC, Emmyn5600 commented on index.html
> +                </button>
On the buttons, kindly implement the hover `color` and make it a `cursor: pointer`.

2022-04-23 10:22 UTC, Emmyn5600 requested changes
Hi @Mugiira-Kim 

Good job so far! I know you have worked hard on making this milestone. There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## Required Changes :recycle:
- [ ] Check the comments under the review too.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!:clap::clap::clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 17:51 UTC, danielufeli approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi @Mugiira-Kim
## Congratulations 🎉 Thank you for implementing all the requirements stated by the previous reviewer🙏

 ![](https://media4.giphy.com/media/DEQPn2GWwjYzUqABzl/200.gif)

### Please go ahead and merge the branch!

## Happy Coding 👏👏👏
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me @danielufeli in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-23 18:01 UTC, merged